##############################################
# API EXTERNA - NASA
##############################################
# URL base de la API de la NASA
nasa.url=https://api.nasa.gov/
# Endpoint específico para la imagen astronómica del día (APOD)
nasa.url.planetary.apod=planetary/apod
# Clave de API (usa DEMO_KEY o tu propia API Key)
nasa.api.key=W5QhN2myPJSxg5VxD6tE3cZWyr5liXTZOL5jHdVD

##############################################
# INFORMACIÓN DE LA APLICACIÓN
##############################################
spring.application.name=@project.name@
application-description=@project.description@
application-version=@project.version@

# Puerto y contexto base
server.port=8085
server.servlet.context-path=/@project.name@


##############################################
# SWAGGER / OPENAPI
##############################################
# Ruta personalizada para Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta para los documentos OpenAPI
springdoc.api-docs.path=/api-docs
# Desactiva respuestas genéricas automáticas
springdoc.override-with-generic-response=false


##############################################
# MONITOREO Y MÉTRICAS (Actuator + Prometheus)
##############################################
# Endpoints expuestos
management.endpoints.web.exposure.include=health,metrics,circuitbreakers,prometheus
# Habilita exportación de métricas para Prometheus
management.metrics.export.prometheus.enabled=true
# Habilita endpoint /actuator/prometheus
management.endpoint.prometheus.enabled=true


##############################################
# CONFIGURACIÓN DE CIRCUIT BREAKER (Resilience4j)
##############################################
# Nombre del circuito: nasaApi
resilience4j.circuitbreaker.instances.nasaApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.nasaApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.nasaApi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.nasaApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.nasaApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.nasaApi.automaticTransitionFromOpenToHalfOpenEnabled=true
